### ISSUE TITLE
Unable to pinpoint location or chat with team

### ISSUE THREAD

**Issue by christyleos** [betterangels/buoy#157]
- Platform: iPhone6S 9.3.4 (13g35)
- Browser: Safari
- URL: http://www.techforjustice.org/wp-admin/?page=buoy_chat&buoy_hash=955298705011d97dfcad3df85b9f896dd072e26189e37a32aa62f93d455c5473&buoy_nonce=d306490ae0
- Is it reproducible: Occasionally
# Steps to Produce/Reproduce
1. User made a team and added 3 members one by one
2. User sent out an invite and once everyone joined by email, user hit the Buoy button.
3. User saw the pop up message for emergency services, then closed it out. At no point did a “ok to use location” notification pop up.
4. User entered the chat room and saw a message from a team member, but did not see a map.
5. Despite hitting 'zoom to fit' and 'go to my location', the map is showing a greyish blue background
6. User typed out a message, but none of them have gone through. 
# Expected Results

User expected to see a map showing user's location and to be able to chat with user's team members. 
# Actual Results

User does not see a map of user's location and is not able to chat with team. 
# Other Information

There was a recent update for the iPhone, which user did not update.

**Comment by fabacab** [comment]
Thanks for this issue report.

Has TechForJustice.org updated its Buoy to the latest release version (0.3.1), released last week? What version of Buoy is being run when this problem surfaces? (This is really helpful to add to issue reports if you know it. I will also add this field to our issue template so future reporters remember to find it.)

**Comment by christyleos** [comment]
Yes, Version 0.3.1 was being used yesterday when the bug occurred. (And will do.)

**Comment by fabacab** [comment]
Short answer:
- for the geolocation issue, you probably need to ensure your Buoy is served over HTTPS, not just HTTP.
- I could not reproduce the chat problem.

In the future, please remember to discuss one issue per issue report. Combining multiple issues into one issue report makes it hard to label, organize, and divvy up work on issues. See also our wiki page on "[Submitting a bug report](https://github.com/betterangels/buoy/wiki/Submitting-a-bug-report)."

Full answer:

I tested this on an iPhone running iOS 9.3.2 and then again after updating the same iPhone to iOS 9.3.5. I was _unable_ to reproduce the geolocation failure issue on the earlier version, but _was_ able to reproduce the issue on the later (current) iOS version.

I believe this is because WebKit (and thus the Safari browser) now only permits geolocation features to be used from secure origins (HTTPS domains). I couldn't find good documentation about this from Apple but did find [this changeset in their issue tracker](https://trac.webkit.org/changeset/200686). Specifically, [this code](https://trac.webkit.org/changeset/200686/trunk/Source/WebCore/Modules/geolocation/Geolocation.cpp) silently blocks geolocation requests when the site is served over HTTP and not HTTPS emitting only a log message not visible to end users. I don't know exactly what version of iOS this code was shipped in, but clearly it was after 9.3.2 and before 9.3.5. :)

The good news is that this isn't actually a bug in Buoy per se, because when I switched my testing server to use HTTPS, instead of HTTP, geolocation worked fine again.

What this means for you:
1. Double check that you have [enabled Location Services](https://support.apple.com/en-us/HT204690) in your iOS device's Privacy settings.
2. Further ensure that if you're using Buoy as an installed app and not just in your browser, the Buoy app itself has permission to use location services.
3. If Buoy still is never able to get your location, you will need to make your Buoy website (techforjustice.org) available via HTTPS (https://techforjustice.org/). Right now, it's not. :( This is a server-admin thing. I can help you to do that if you need to, but we should talk about that over email or some other less-public channel, because it may require you to give me access to your server or webhost configuration or account if you need a lot of help with this.

Also, if you're just _testing_ Buoy, then you might find it easier to use the staging server I set up for this exact purpose, because it is available over HTTP and HTTPS specifically to test for cases like this. In that case, join us in our [public developer chat room](https://gitter.im/betterangels/buoy), say hi, and let one of know you want to test Buoy, and we'll direct you to the semi-private staging server.

Finally, go ahead and update your iPhone to the latest version, as it wants you to do. You don't need to stay on iOS 9.3.4 and should update to 9.3.5 ASAP.
