### ISSUE TITLE
Buoy issues

### ISSUE THREAD

**Issue by the-phoebe** [betterangels/buoy#220]
A brief summary of the issue.

OK, here goes my breakdown of Buoy (cover page), then delving into the issues with various parts of the on boarding process (pages 1-5)

https://drive.google.com/file/d/0B5lzGDr3bT1XdnBudlRxQ1RGeDg/view?usp=sharing

First and most importantly though is to figure out how to keep the Buoy invites (sent to Crisis Response Team members) from getting routed immediately to the Junk folder. In the CRT member's Junk folder, the invite shows the sender as "wordpress@carryon.online". I wonder if it has anything to do with the domain name (after the "@" symbol)?

Page 1: (1a) and (1b) - issue: email routed to Spam folder
Page 5: (1b) - issue: never ending "loading" status
(2b) - issue: map/GPS location not showing
(3b) - issue: "record" button(s) not working
(4b) - issue: "video recording" button not working
(5b) - issue: tlk.io chat not working (I sent a message from "menchies" (my bf's phone) saying "u ok?", but I never got this message on my phone; then I sent a message from my phone in the tlk.io chat to "menchies", but this message was never received on his phone) (edited)

* Buoy version: 0.3.3
* Platform: Mac
* Browser: Google Chrome & Safari
* URL: https://drive.google.com/file/d/0B5lzGDr3bT1XdnBudlRxQ1RGeDg/view?usp=sharing
* Is it reproducible: Yes

# Steps to Produce/Reproduce

Follow along with the steps outlined in this document:

https://drive.google.com/file/d/0B5lzGDr3bT1XdnBudlRxQ1RGeDg/view?usp=sharing

# Expected Results

- Invitation to Crisis Response Team emails routed immediately to Spam folder
- Confirmation email (after creating an acct on Wordpress) routed immediately to Spam folder
- After sending distress signal, constant "loading" status
- map/GPS location not showing
- "record" buttons not working
- "video recording" button not working
- tlk.io chat not working (messages are neither received/sent successfully)

# Actual Results

- Invitation to Crisis Response Team emails routed immediately to Spam folder
- Confirmation email (after creating an acct on Wordpress) routed immediately to Spam folder
- After sending distress signal, constant "loading" status
- map/GPS location not showing
- "record" buttons not working
- "video recording" button not working
- tlk.io chat not working (messages are neither received/sent successfully)

# Workarounds

I have absolutely no idea. :-/

# Other Information

Y'all can contact me at pearquero@gmail.com if you need to.

**Comment by fabacab** [comment]
Thanks for taking the time to look into these. Unfortunately, I'm closing this immediately as it is basically an unusable issue report due to multiple issues. Please see [Submitting a bug report](https://github.com/betterangels/buoy/wiki/Submitting-a-bug-report) on our wiki for help on composing useful issue reports. In the future:

* Please create separate issue tickets for separate issues.
* Supply a meaningful title summarizing the individual issue to which the report relates.
* Use the issue template in a meaningful way; for instance, it makes no sense for the "actual results" and "expected results" to be identical, for (obvious?) reasons.
* Search for similar issues to the ones you're having in this issue tracker and comment on those threads instead of posting duplicated ones; for instance, the video buttons being broken (#216), and on modern browsers, geolocation only works with an HTTPS page and this is remarked on in many other places (#161, #157).

Anyway, I kind of want to file a bug report on this bug report because there's too much in-actionable correspondence here. :(
